name: Lint and test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run ts-check
